src/blog/urls.py
from django.conf.urls import url 
from django.views.generic.base import RedirectView
from blog import views

urlpatterns = [
	url(r'detail/(?P<pk>\d+)/like', views.PostLikeToggle.as_view(), name='like-toggle'),
	url(r'create/', views.create_post, name='create'),
    url(r'detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),

    url(r'update/(?P<pk>\d+)', views.PostUpdateView, name='update'),
    url(r'file/delete/(?P<pk>\d+)', views.image_delete, name='file-delete'),
    url(r'post/delete/(?P<pk>\d+)', views.post_delete, name='post-delete'),
    # url(r'', RedirectView.as_view(url="home")),

]

src/grades/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from grades import views

urlpatterns = [
    url(r'detail/(?P<pk>\d+)', views.GradeDetailView.as_view(), name='detail'),
    url(r'list/', views.PostListView.as_view(), name='list'),
]

src/school/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts  import views as accounts_views
from blog.views import PostListView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    # url(r'^', include('events.urls', namespace='events')),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/student$', accounts_views.StudentSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='student_signup'),
    url(r'^signup/teacher$', accounts_views.TeacherSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='teacher_signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'api/blog/', include('blog.api.urls', namespace='api_blog')),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'marks/', include('marks.urls', namespace='marks')),
    url(r'grades/', include('grades.urls', namespace='grade')),
    url(r'events/', include('events.urls', namespace='events')),
    url(r'^$',  accounts_views.HomeListView.as_view(), name='home'),
    #url(r'ckeditor/', include('ckeditor_uploader.urls', )),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from grades.models import Grade
import os
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    title = models.CharField(max_length=120)
    content = RichTextField(config_name='awesome_ckeditor', blank=True, null=True, max_length=2000)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, related_name="posts", blank=True, null=True)
    like = models.ManyToManyField(User, related_name="likes", blank=True,)
    draft = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

    def get_like_url(self):
        return reverse('blog:like-toggle', args=[str(self.id)])

    def get_like_api_url(self):
        return reverse("api_blog:like-api-toggle", args=[str(self.id)])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-updated", "-timestamp", ]
        verbose_name_plural = "Posts"


class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    default = models.BooleanField(default=False)
    post = models.ForeignKey(
        Post, related_name="images", on_delete=models.CASCADE,)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

    def filename(self):
        return os.path.basename(self.image.name)

    def __str__(self):
        return self.post.title
    # width = models.FloatField(default=100)
    # length = models.FloatField(default=100)

src/grades/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, UpdateView, CreateView, RedirectView
from .models import Grade
# Create your views here.


class GradeDetailView(DetailView):
    model = Grade
    context_object_name = 'grade'
    template_name = 'grades/grade_detail.html'


class PostListView(ListView):
    template_name = 'grades/grade_list.html'
    context_object_name = 'grades'
    queryset = Grade.objects.all()

src/templates/nav.html
{% load static %}
 <!-- Navbar -->
  <nav class="navbar bg-white fixed-top container d-block">

<div class="container  navbar-translate">

		<a href="{% url 'home' %}" style="width:clamp(180px,50%,250px);">
		   <img src="{% static 'img/logo.png' %}" alt="logo">
		 </a>
		 <button class="navbar-toggler navbar-toggler last" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
		     <i class="fas fa-th"></i>
		 </button>
		 	 
		 <div  class="collapse navbar-collapse py-3" id="navigation">
            <ul class="navbar-nav flex-column ">
            	 <li class="nav-item" >
                	 <form class="bg-default-light"  action="{% url 'home' %}" method="GET">

						<input class="form-control form-control-no-border" type="text" name="q" placeholder='بحث...' value="{{ request.GET.q }}">
						<button style="display:none" class="btn btn-primary btn-simple" type='submit' value='search'>Search</button>

					</form>
                </li>
                {% if not user.is_authenticated %}<li class="nav-item">
                    <a  class="nav-link" href="{% url 'login' %}"><strong>تسجيل الدخول</strong></a>
                </li>{% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'grade:list' %}"><strong>مواضيع الإختبارات</strong> </a>
                </li>


            </ul>
        </div>

</div>
</nav>

src/templates/navb.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-default  fixed-bottom mb-0" color-on-scroll="400">
	<div style="font-size: x-large;"class="container d-flex nav-justified">
		<a class="nav-icon text-capitalize" href=""><span class="mr-2"><i class="far fa-caret-square-left"></i></span>back</a>
		<img src="{% static 'img/logo-aladin.png' %}"" width="30" height="30" alt="logo">
		<a class="nav-icon text-capitalize" href=""><span class="mr-2"><i class="fas fa-home"></i></span>log in</a>
	</div>
	
</nav>
<nav class="navbar navbar-expand-lg  fixed-bottom  justify-content-center" color-on-scroll="400">
	<a class="text-larg"><span class="bg-default p-4 circle"><i class="fas fa-plus"></i></span></a>
</nav>

src/templates/navbar-loggedin.html
{% load static %}
{% if request.user.is_student %}
 <!-- Navbar -->
	    <nav class="navbar navbar-expand-lg bg-default fixed-top p-0 " color-on-scroll="400">
	        <div class="container flex-nowrap">
	            <div >
	            	 <a class="navbar-brand mx-auto" href="#">
	                  <img src="{% static 'img/logo-aladin.png' %}"" width="30" height="30" alt="logo">
					 	<p>Aladin Private School</p>
	                </a>
	            </div>
	           
	            <form class="form-inline flex-nowrap fb" id="navSearch" action="{% url 'home' %}" method="GET">
	
					<input class="form-control form-control-no-border" type="text" name="q" placeholder='Search...' value="{{ request.GET.q }}">
					<button style="display:none" class="btn btn-primary btn-simple" type='submit' value='search'>Search</button>
				
				</form> 
	            
	           
	            <div class="d-flex fb" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">

	                <ul class="navbar-nav">
	                	 <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'home' %}"><i class="fas fa-home"></i></a>
	                    </li>
	                    <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'accounts:profile' request.user.username %}"><i class="fas fa-user"></i></a>
	                    </li>
	                    <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'accounts:grade' request.user.students.classroom.name %}"><i class="fas fa-users"></i></a>
	                    </li>
	                    <li class="nav-item">
	                    	<a class="nav-link btn-round" href=""><i class="fas fa-bell"></i></a>
	                    </li>
	                </ul>
	                <div class="nav-item dropdown">
	                       <a class="nav-link dropdown-toggle"  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	                       	{% if user.avatar %}
	                       	<img style="max-width: 35px; max-height: 35px;" class="rounded-circle" src="{{ request.user.avatar.url }}">
	                       	{% else %}
	                       	{% endif %}
	                         
	                       </a>
	                       <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	                         <a class="dropdown-item" href="{% url 'accounts:update' request.user.username %}">Update Profile</a>
	                         <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> 
	                       </div>
	                </div>
	            </div>

	        </div>
	    </nav>
	    

{% endif %}
{% if request.user.is_teacher %}
<!-- Navbar -->
	    <nav class="navbar navbar-expand-lg bg-default fixed-top p-0 " color-on-scroll="400">
	        <div class="container flex-nowrap">
	            <div >
	            	 <a class="navbar-brand mx-auto" href="#">
	                  <img src="{% static 'img/logo-aladin.png' %}"" width="30" height="30" alt="">
					 	<p>Aladin Private School</p>
	                </a>
	            </div>
	           
	            <form class="form-inline flex-nowrap fb" id="navSearch" action="{% url 'home' %}" method="GET">
	
					<input class="form-control form-control-no-border" type="text" name="q" placeholder='Search...' value="{{ request.GET.q }}">
					<button style="display:none" class="btn btn-primary btn-simple" type='submit' value='search'>Search</button>
				
				</form> 
	            
	           
	            <div class="d-flex fb" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">

	                <ul class="navbar-nav">
	                	 <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'home' %}"><i class="fas fa-home"></i></a>
	                    </li>
	                    <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'accounts:profile' request.user.username %}"><i class="fas fa-user"></i></a>
	                    </li>
	                    <li class="nav-item dropdown">
	                    	<a class="nav-link dropdown-toggle"  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-users"></i></a>
	                    	<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	                    		{% for obj in request.user.teachers.classroom.all %}
	                         <a class="dropdown-item" href="{% url 'accounts:grade' obj.name %}">{{ obj.name }}</a>
	                         	{% endfor %}
	                       </div>
	                    	
	                    </li>
	                    <li class="nav-item">
	                    	<a class="nav-link btn-round" href=""><i class="fas fa-bell"></i></a>
	                    </li>
	                </ul>
	                <div class="nav-item dropdown">
	                       <a class="nav-link dropdown-toggle"  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	                       	{% if user.avatar %}
	                       	<img style="max-width: 35px; max-height: 35px;" class="rounded-circle" src="{{ request.user.avatar.url }}">
	                       	{% else %}
	                       	{% endif %}
	                         
	                       </a>
	                       <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	                         <a class="dropdown-item" href="{% url 'accounts:update' request.user.username %}">Update Profile</a>
	                         <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> 
	                       </div>
	                </div>
	            </div>

	        </div>
	    </nav>
{% endif %}
{% if request.user.is_superuser %}
	     <!-- Navbar -->
	    	    <nav class="navbar  bg-default navbar-transparent fixed-top container d-block" color-on-scroll="400">
	    	            <div class="navbar-translate d-flex justify-content-between align-items-center">
	    	               <a class="navbar-brand" href="{% url 'home' %}">
	    	                  <img src="{% static 'img/logo-aladin.png' %}"" width="30" height="30" alt="">
	    					 <strong>مدرسة علاء الدين الخاصة</strong> 
	    	                </a>
	    	                <button class="navbar-toggler navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
	    	                    <i class="fas fa-th"></i>
	    	                </button>
	    	            </div>
	    	            <div class="collapse navbar-collapse justify-content-end" id="navigation">
	    	                <ul class="navbar-nav justify-content-end">
	    	                	<li class="nav-item">
	    	                        <a class="nav-link btn-round" href="{% url 'logout' %}">Logout</a> 
	    	                    </li>
	    	                    <li class="nav-item">
	    	                        <a class="nav-link btn-round" href="{% url 'home' %}"><i class="fas fa-home"></i></a>
	    	                    </li>
	    	                    
	    	                </ul>
	    	            </div>
	    	        
	    	    </nav>
	    	    
{% endif %}

src/templates/navbar-loggedout.html
{% load static %}
 <!-- Navbar -->
	    <nav class="navbar  bg-default navbar-transparent fixed-top container d-block" color-on-scroll="400">
	            <div class="navbar-translate d-flex justify-content-between align-items-center">
	               <a class="navbar-brand" href="{% url 'home' %}">
	                  <img src="{% static 'img/logo-aladin.png' %}"" width="30" height="30" alt="logo">
					 <strong>مدرسة علاء الدين الخاصة</strong> 
	                </a>
	                <button class="navbar-toggler navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
	                    <i class="fas fa-th"></i>
	                </button>
	            </div>
	            <div class="collapse navbar-collapse justify-content-end" id="navigation">
	                <ul class="navbar-nav justify-content-end">
	                    <li class="nav-item">
	                        <a class="nav-link" href="#"><strong>Create Account</strong> </a>
	                    </li>
	                    <li class="nav-item">
	                        <a class="nav-link" href="{% url 'login' %}"><strong>Login</strong></a>
	                    </li>
	                </ul>
	            </div>
	        
	    </nav>
	    

src/templates/post_create.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block content%}

	<div class="nav-spacing py-5"></div>
	<div class="container">
		<div class="row">
				<div class="card cold-md-8  ">
				<form  action="" method="post" enctype="multipart/form-data">{% csrf_token %}
				{{ form.media }}
				<div class="input-group">
				  <div class="input-group-prepend">
				    <span class="btn btn-danger m-0" type="button">title</span>
				  </div>
				  {% render_field form.title class="form-control" %}
				</div>
				<div class="input-group">
				  <div class="input-group-prepend">
				    <span class="btn btn-danger m-0" type="button">title</span>
				  </div>
				  {% render_field form.grade class="form-control" %}
				</div>
				<div class="for">

			    </div>
			    <p>
			    <pre class="mx-auto">
			    {% render_field form.content class="form-control" %}
			    </pre>
			    </p>
			    <div class="form-group m-4">
			    {% render_field form.draft  %}
			    <label class="custom-control-label mt-3">draft</label>
			    </div>
			    <!-- <input required type="file" multiple name="images" class="form-control_file"> -->
			    <div class="d-block custom-file">
			      <input name="images" type="file" multiple class="" id="id_images">
			    </div>
			    <input type="submit" value="Save" />
			</form>
			</div>


		</div>
	</div>

{% endblock %}

src/templates/post_detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}{{ grade.name }}{% endblock title %}
{% block content%}
<style >
	.images:hover {
		background: rgba(0,0,0,0.5);
	}
	.images {
		max-height: 100px;
	}
	.overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  opacity: 0;
  transition: .5s ease;
  background-color: rgba(44,168,255,0.5);
}
.overlay:hover {
	opacity: 1;
}
.text {
  color: white;
  position: absolute;
  top: 20%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
</style>

<div class="nav-spacing">
	<h3>{{ grade.name }}</h3>
	{% if messages%}
	{% for msg in messages %}
	<div class="alert bg-success text-white text-center">{{ msg  }} </div>
	{% endfor %}
	{% endif %}
</div>

<div class="container">
	{% if request.user == post.user or request.user.is_superuser %}
	<div class="fixed-bottom">
		<a href="{% url 'blog:update' post.pk %}" class="coffee-button text-white p-4  circle"><i class="far fa-edit"></i></a>
	</div>
	{% endif %}
	<div class="row">
		<div class="col-md-10 mx-auto bg-white my-3 p-5">
			<article>
			<h2 class="text-center">{{ post.title }}</h2><hr/>
			<p style="word-break: break-word;">{{ post.content|safe }}</p><hr/>
		</article>
		<a class="btn btn-info" href="{% url 'home' %}">retour</a>
		</div>
		{% if image_list %}
		<div class="col-md-10 mx-auto bg-white my-3 p-5">
			<strong >image attachment click to download</strong>
			<div class="row my-5">
			{% for obj in image_list %}
     		 <div class="col-4 images my-3">

			<a  href="{{ obj.image.url }}"><img style="height: 100%;max_height:100px;width:100%;" src="{{ obj.image.url }}" alt="obj.image" class="">
				<div class="overlay"><p class="text">click to download</p>
					{% if  request.user.is_superuser or request.user == posts.user %}
     		 		<a href="{% url 'blog:file-delete' obj.pk %}"><span class="close-btn"><i class="fas fa-times fa-2x"></i></span></a>
     		 	{% endif %}
			  </div></a>

			</div>
			 {% endfor %}
			</div></div>
			 {% endif %}
			{% if file_list %}
			<div class="col-md-10 mx-auto bg-white my-3 p-5">
			<strong >file attachment click to download</strong>

			<div class="row my-5">
			{% for obj in file_list %}
           <div class="col-4 images  p-5">
           	<div class="row">
      <a  href="{{ obj.image.url }}"><div class="text-white"><i class="fa fa-file fa-3x text " aria-hidden="true"></i>
			</i></div><div class="overlay">{% if  request.user.is_superuser or request.user == posts.user %}
     		 		<a href="{% url 'blog:file-delete' obj.pk %}"><span class="close-btn"><i class="fas fa-times fa-2x"></i></span></a>
     		 	{% endif %}</div></a></div>
        <div style="position: absolute; bottom: 20%;" class="mx-auto">
				{{ obj.filename|truncatechars:20}}
			</div>
      </div>
			{% endfor %}
			</div>


		</div>
			{% endif %}



			</div>




		</div>
	</div>



</div>
{% endblock %}

src/templates/post_list.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content%}
<div class="container">
<h1>BLog List</h1>
<form action="{% url 'home' %}" method="GET">
	<input type="text" name="q" palceholder='searrch' value="{{ request.GET.q }}">
	<input type='submit' value='search'>
</form>
	
	<div class="row">
		<div class="col-md-8">

	{% for post in posts %}
	
		<p> <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a> </p>
		<p>{{ post.content }}</p>
	
		<img src="{{ post.image.url }}">
		{% if post.updated %}
		<p>Updated : {{ post.updated|timesince }} ago</p><hr/><hr/>
		{% else %}
		<p>Created{{ post.timestamp|timesince }} ago </p>
		{% endif %}
		
		<p>author : {{ post.user.get_full_name }}</p>
		{% if  post.user == request.user%}
			<button class="btn btn-info"><a href="{% url 'blog:update' post.id %}">Update</a></button>

		{% endif%}
	{% empty %}
			{% if request.GET.q %}
			<p>no post found</p>
			{% else %}
			<p> no posts yet</p>
			{% endif %}

	{% endfor %}
		</div>
	</div>
	

{% endblock %}

src/templates/posts_update_form.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content%}
<style >
    .images:hover {
        background: rgba(0,0,0,0.5);
    }
    .overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  opacity: 0;
  transition: .5s ease;
  background-color: rgba(44,168,255,0.5);
}
.overlay:hover {
    opacity: 1;
}
.text {
  color: white;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
</style>

    <div class="nav-spacing"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-10 mx-auto bg-white my-3 p-5">

            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                 <div class="custom-file">
                  <input placeholder="upload" name="images" type="file" multiple class="" id="id_images">
                </div>
               <p class="my-3 d-inline"><label for="id_default">Files ?:</label>
                   <input id="id_default" name="default" type="checkbox" class="">
               </p>


                <input class="d-block" type="submit" value="Update" />
            </form>
            </div>
<div class="col-md-10 mx-auto bg-white my-3 p-5">
      <strong >attachment</strong>
      <div class="row mt-5">
      {% for obj in post.images.all %}
             {% if obj.default %}
      <div class="col-4 images m-3 p-0">
      <a  href="{{ obj.image.url }}"><div class="text-white  w-100 h-100"><i class="fa fa-file fa-4x text" aria-hidden="true"></i>
            </i></div><div class="overlay">
        </div></a></div>
      {% else %}

      <div class="col-4 images m-3 p-0">
            <a  href="{{ obj.image.url }}"><img style="max_height:100px;width:100%;" src="{{ obj.image.url }}" alt="obj.image" class=""><div class="overlay"><p class="text">{{ext}}</p>
            <a style="font-size: 30px;position: absolute;top: -10px;right: 5px; "class="text-white"href="{% url 'blog:file-delete' obj.pk %}" type="button" class="close"  aria-label="Close">
          <span aria-hidden="true">&times;</span></a>
              </div></a>

            </div>
                    {% endif %}
      {% endfor %}
      </div>
      </div>
        </div>
    </div>
</div>
      {% endblock content %}