src/blog/urls.py
from django.conf.urls import url 
from django.views.generic.base import RedirectView
from blog import views

urlpatterns = [
	url(r'detail/(?P<pk>\d+)/like', views.PostLikeToggle.as_view(), name='like-toggle'),
	url(r'create/', views.create_post, name='create'),
    url(r'detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),

    url(r'update/(?P<pk>\d+)', views.PostUpdateView, name='update'),
    url(r'file/delete/(?P<pk>\d+)', views.image_delete, name='file-delete'),
    url(r'post/delete/(?P<pk>\d+)', views.post_delete, name='post-delete'),
    # url(r'', RedirectView.as_view(url="home")),

]

src/grades/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from grades import views

urlpatterns = [
    url(r'detail/(?P<pk>\d+)', views.GradeDetailView.as_view(), name='detail'),
    url(r'list/', views.PostListView.as_view(), name='list'),
]

src/school/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts  import views as accounts_views
from blog.views import PostListView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    # url(r'^', include('events.urls', namespace='events')),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/student$', accounts_views.StudentSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='student_signup'),
    url(r'^signup/teacher$', accounts_views.TeacherSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='teacher_signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'api/blog/', include('blog.api.urls', namespace='api_blog')),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'marks/', include('marks.urls', namespace='marks')),
    url(r'grades/', include('grades.urls', namespace='grade')),
    url(r'events/', include('events.urls', namespace='events')),
    url(r'^$',  accounts_views.HomeListView.as_view(), name='home'),
    #url(r'ckeditor/', include('ckeditor_uploader.urls', )),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/grades/models.py
from django.db import models
from accounts.models import User, Teacher, Module, Grade

# Create your models here.


class Grade(models.Model):
    niveau = (
        ('الإبتدائي', 'الإبتدائي'),
        ('المتوسط', 'المتوسط'),
        ('الثانوي', 'الثانوي'),
    )
    name = models.CharField(max_length=50, unique=True)
    level = models.CharField(max_length=30, choices=niveau, )

    def get_absolute_url(self):
        return reverse('grade:detail', args=[str(self.id)])

    def __str__(self):
        return self.name

src/grades/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, UpdateView, CreateView, RedirectView
from .models import Grade
# Create your views here.


class GradeDetailView(DetailView):
    model = Grade
    context_object_name = 'grade'
    template_name = 'grades/grade_detail.html'


class PostListView(ListView):
    template_name = 'grades/grade_list.html'
    context_object_name = 'grades'
    queryset = Grade.objects.all()

src/templates/grades/grade_detail.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content%}
<style >
	.images:hover {
		background: rgba(0,0,0,0.5);
	}
	.images {
		max-height: 100px;
	}
	.overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  opacity: 0;
  transition: .5s ease;
  background-color: rgba(44,168,255,0.5);
}
.overlay:hover {
	opacity: 1;
}
.text {
  color: white;
  position: absolute;
  top: 20%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
</style>

<div class="nav-spacing">

	{% if messages%}
	{% for msg in messages %}
	<div class="alert bg-success text-white text-center">{{ msg  }} </div>
	{% endfor %}
	{% endif %}
</div>

<div class="container">
	<div class="row">
		<h5>{{ grade.name }}</h5>
	</div>
	<div class="row">
		<div class="col-md-10">

	{% for post in grade.posts.all %}
	
		<p> <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a> </p>
		<div class="d-none d-sm-block">
		<p>{{ post.content }}</p>
	
		<img src="{{ post.image.url }}">
		{% if post.updated %}
		<p>Updated : {{ post.updated|timesince }} ago</p><hr/><hr/>
		{% else %}
		<p>Created{{ post.timestamp|timesince }} ago </p>
		{% endif %}
		
		<p>author : {{ post.user.get_full_name }}</p></div>
		{% if  post.user == request.user%}
			<button class="btn btn-info"><a href="{% url 'blog:update' post.id %}">Update</a></button>

		{% endif%}
	{% empty %}
			{% if request.GET.q %}
			<p>no post found</p>
			{% else %}
			<p> no posts yet</p>
			{% endif %}

	{% endfor %}
		</div>
	</div>


</div>
{% endblock %}