src/blog/urls.py
from django.conf.urls import url 
from django.views.generic.base import RedirectView
from blog import views

urlpatterns = [
	url(r'detail/(?P<pk>\d+)/like', views.PostLikeToggle.as_view(), name='like-toggle'),
	url(r'create/', views.create_post, name='create'),
    url(r'detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),

    url(r'update/(?P<pk>\d+)', views.PostUpdateView, name='update'),
    url(r'file/delete/(?P<pk>\d+)', views.image_delete, name='file-delete'),
    url(r'post/delete/(?P<pk>\d+)', views.post_delete, name='post-delete'),
    # url(r'', RedirectView.as_view(url="home")),

]

src/events/urls.py
from django.conf.urls import url
from events import views


urlpatterns = [
	url(r'', views.EventCreate.as_view() ,name='teacher'),
]
    

src/grades/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from grades import views

urlpatterns = [
    url(r'detail/(?P<pk>\d+)', views.GradeDetailView.as_view(), name='detail'),
    url(r'list/', views.PostListView.as_view(), name='list'),
]

src/school/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts  import views as accounts_views
from blog.views import PostListView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    # url(r'^', include('events.urls', namespace='events')),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/student$', accounts_views.StudentSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='student_signup'),
    url(r'^signup/teacher$', accounts_views.TeacherSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='teacher_signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'api/blog/', include('blog.api.urls', namespace='api_blog')),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'marks/', include('marks.urls', namespace='marks')),
    url(r'grades/', include('grades.urls', namespace='grade')),
    url(r'events/', include('events.urls', namespace='events')),
    url(r'^$',  accounts_views.HomeListView.as_view(), name='home'),
    #url(r'ckeditor/', include('ckeditor_uploader.urls', )),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from grades.models import Grade
import os
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    title = models.CharField(max_length=120)
    content = RichTextField(config_name='awesome_ckeditor', blank=True, null=True, max_length=2000)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, related_name="posts", blank=True, null=True)
    like = models.ManyToManyField(User, related_name="likes", blank=True,)
    draft = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

    def get_like_url(self):
        return reverse('blog:like-toggle', args=[str(self.id)])

    def get_like_api_url(self):
        return reverse("api_blog:like-api-toggle", args=[str(self.id)])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-updated", "-timestamp", ]
        verbose_name_plural = "Posts"


class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    default = models.BooleanField(default=False)
    post = models.ForeignKey(
        Post, related_name="images", on_delete=models.CASCADE,)

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

    def filename(self):
        return os.path.basename(self.image.name)

    def __str__(self):
        return self.post.title
    # width = models.FloatField(default=100)
    # length = models.FloatField(default=100)

src/events/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone

# Create your models here.


class Event(models.Model):
	user    = models.ForeignKey(User, on_delete=models.CASCADE , related_name='events')
	content = models.CharField(max_length=120)
	start   = models.DateField(auto_now=False, auto_now_add=False)
	end     = models.DateField(auto_now=False, auto_now_add=False)

	# def EventMessage(request):

	# 	qs = Event.objects.filter(start__lte=timezone.now().date(),end__gte=timezone.now().date(),user=request.user)
	# 	Event.objects.filter(end__lte=timezone.now().date()).delete()

	def __str__(self):
		return self.content

src/grades/models.py
from django.db import models
from accounts.models import User, Teacher, Module, Grade

# Create your models here.


class Grade(models.Model):
    niveau = (
        ('الإبتدائي', 'الإبتدائي'),
        ('المتوسط', 'المتوسط'),
        ('الثانوي', 'الثانوي'),
    )
    name = models.CharField(max_length=50, unique=True)
    level = models.CharField(max_length=30, choices=niveau, )

    def get_absolute_url(self):
        return reverse('grade:detail', args=[str(self.id)])

    def __str__(self):
        return self.name

src/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from itertools import chain
from operator import attrgetter
from .models import User, Teacher, Student, Grade
from .forms import StudentSignUpForm, TeacherSignUpForm, UserForm, TeacherForm, StudentForm
from events.models import Event
from blog.models import Post
from marks.models import Marks


#@method_decorator(login_required, name='dispatch')
class HomeListView(ListView):
    template_name = 'accounts/home_list.html'
    context_object_name = 'list'

    def get_queryset(self):
        qs1 = ""  # Marks.objects.filter(user=self.request.user)
        #qs2 = Event.objects.all()
        current_user = self.request.user
        if current_user.is_superuser:
            qs3 = Post.objects.all()
        else:
            qs3 = Post.objects.filter(draft=False)
        queryset = sorted(
            chain(qs1, qs3),
            key=attrgetter('timestamp'),
            reverse=True)
        query = self.request.GET.get('q', None)
        if query is not None:
            queryset = qs3.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query)
            )

        return queryset


'''
SIGN UP VIEWS FOR STUDENT AND TEACHERS

'''


class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'accounts/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'accounts/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')


'''
USER PROFILE VIEW FOR BOTH STUDENT/TEACHERS 
'''


@method_decorator(login_required, name='dispatch')
class ProfileDetailView(DetailView):
    template_name = 'accounts/profile.html'
    queryset = User.objects.all()

    def get_object(self):
        return get_object_or_404(User, username__iexact=self.kwargs.get('username'))


# class ProfileListView(ListView):
#     template_name = 'accounts/profile_list.html'
#     context_object_name = 'profile_list'
#     queryset = User.objects.all()
#


'''
School Grade/Class List View 
'''


@method_decorator(login_required, name='dispatch')
class GradeDetailView(DetailView):
    template_name = 'accounts/grade.html'
    queryset = Grade.objects.all()

    def get_object(self):
        return get_object_or_404(Grade, name__iexact=self.kwargs.get('name'))


@login_required()
def edit_profile(request, username):
    # querying User objects with username and Profile with id
    user = User.objects.get(username=username)
    if user.is_teacher:
        profile = Teacher.objects.get(id=user.teachers.id)
        profile_form = TeacherForm(instance=profile)
    if user.is_student:
        profile = Student.objects.get(id=user.students.id)
        profile_form = StudentForm(instance=profile)

    user_form = UserForm(instance=user)

    # making suer the user is authenticated and is the same user

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == "POST":
            if user.is_teacher:
                profile_form = TeacherForm(request.POST, request.FILES, instance=profile)
                user_form = UserForm(request.POST, request.FILES, instance=user)

            if user.is_student:
                profile_form = StudentForm(request.POST, request.FILES, instance=profile)
                user_form = UserForm(request.POST, request.FILES, instance=user)

            if profile_form.is_valid() and user_form.is_valid():
                created_profile = profile_form.save(commit=False)
                user_form.save()
                created_profile.save()
                return redirect('home')

        return render(request, 'accounts/update.html', {"noodle": username, "noodle_form": user_form, "formset": profile_form})
    else:
        raise PermissionDenied

src/grades/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, UpdateView, CreateView, RedirectView
from .models import Grade
# Create your views here.


class GradeDetailView(DetailView):
    model = Grade
    context_object_name = 'grade'
    template_name = 'grades/grade_detail.html'


class PostListView(ListView):
    template_name = 'grades/grade_list.html'
    context_object_name = 'grades'
    queryset = Grade.objects.all()

src/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/logo-aladin.png' %}">
    <link rel="icon" type="image/png" href="{% static 'img/logo-aladin.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}Aladin Primary School{% endblock title %} </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" /> -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit/main.css' %}" rel="stylesheet" />

</head>
<body class="bg-white">
    {% block navbar %}

	{% include 'nav.html' %}



    {% endblock navbar %}
	{% block content %}

	{% endblock %}



</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>


<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/now-ui-kit.js' %}" type="text/javascript"></script>

{{ form.media }}

{% block script %} {% endblock %}
</html>

src/templates/accounts/grade.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content%}
<div class="page-header" filter-color="orange">
	<div class="page-header-image" style="background-image:url({% static 'img/a5.jpg' %})"></div>
<div class="nav-spacing"></div>

	<div class="container">

		<h1> Grade : {{ grade.name }}</h1>

		<h6 class="bg-default p-3 mb-0"> Students :  <a data-toggle="collapse" href="#AboutStudent" aria-expanded="false" aria-controls="AboutStudent" class="align-text-top text-white pull-right"><small>HIDE</small></a></h6>
		<div class="card-block p-3 collapse show" id="AboutStudent">
		<div class="row">
		{% for obj in grade.student_set.all %}
		<div class="col-lg-3 col-md-4">
		<div class="card card-profile">
              <img alt="" class="card-img-top" src="{% static 'img/banner.jpg' %}">
              <div class="card-block text-center">
                <a href="{% url 'accounts:profile' obj.user.username %}"><img alt="" class="card-img-profile" src="{% if obj.user.avatar %}{{ obj.user.avatar.url }}{% endif %}"></a>
                <h6 class="mt-3">{{ obj.user.first_name }}  {{ obj.user.last_name }}</h6>
                <a href="{% if obj.user.is_student %}{% url 'accounts:grade' obj.user.students.classroom.name %}{% endif %}"><h6 class="card-subtitle mb-2 badge badge-info">@{% if obj.user.is_student %}{{ obj.user.students.classroom.name}}{% endif %}</h6></a>
                <p class="afo">I wish i was a little bit taller, wish i was a baller, wish i had a girl…&nbsp;also.</p>
            </div>
          </div></div>
		
		{% endfor %}
	</div></div>	
		
		<h6 class="bg-default p-3 mb-0"> Teachers :  <a data-toggle="collapse" href="#AboutTeacher" aria-expanded="false" aria-controls="AboutTeacher" class="align-text-top text-white pull-right"><small>HIDE</small></a></h6>
		<div class="card-block p-3 collapse show" id="AboutTeacher">
		<div class="row">
		{% for obj in grade.teacher_set.all %}

		<div class="col-lg-3 col-md-4">
		<div class="card card-profile">
              <img alt="" class="card-img-top" src="{% static 'img/banner.jpg' %}">
              <div class="card-block text-center">
                <a href="{% url 'accounts:profile' obj.user.username %}"><img alt="" class="card-img-profile" src="{% if obj.user.avatar %}{{ obj.user.avatar.url }}{% endif %}"></a>
                <h6 class="mt-3" >{{ obj.user.first_name }}  {{ obj.user.last_name }}</h6>
                <p class="badge badge-primary">{{ obj.user.teachers.module }}</p>

                <p class="afo">I wish i was a little bit taller, wish i was a baller, wish i had a girl…&nbsp;also.</p>
            </div>
          </div></div>
			
		{% endfor %}
	</div>	
	</div>
</div>
</div>
{% endblock %}

src/templates/accounts/home_list.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block script %}
<script>
     $(document).ready(function(){
          function updateText(btn, newCount){
          /*btn.text( newCount)*/
          btn.attr("data-likes", newCount)
          $(".like-count").text(newCount)

      }
      $(".like-btn").click(function(e){
        e.preventDefault()

        var this_ = $(this)
        var likeUrl = this_.attr("data-href")
        var likeCount = parseInt(this_.attr("data-likes")) | 0
        var addLike = likeCount + 1
        var removeLike = likeCount - 1
        if (likeUrl){
           $.ajax({
            url: likeUrl,
            method: "GET",
            data: {},
            success: function(data){
              console.log(data)
              var newLikes;
              if (data.liked){
                  updateText(this_, addLike,)
              } else {
                  updateText(this_, removeLike,)
                  // remove one like
              }
            }, error: function(error){
              console.log(error)
              console.log("error")
            }
          })
        }

      })
  })
    </script>
{% endblock %}


{% block content%}
	<div class="container mt-5">
		<div class="row">

			<div class="col-lg-8 mx-auto">
				{% include 'accounts/mid-section.html'%}
			</div>

		</div>
	</div>

{% endblock %}

src/templates/accounts/left-section.html
{% load static %}

<div class="card card-profile mt-0">
  <img alt="" class="card-img-top" src="{% static 'img/banner.jpg' %}">
  <div class="card-block p-3 text-center">
    <a href=""><img alt="" class="card-img-profile" src="{% if user.avatar %} {{ user.avatar.url }} {% endif %}"></a>
    <h6 class="mt-3">{{ user.first_name }}  {{ user.last_name }}</h6>
    <a href="{% if user.is_student %}{% url 'accounts:grade' user.students.classroom.name %}{% endif %}">{% if user.is_student %}<h6 class="card-subtitle mb-2 badge badge-info">@{{ user.students.classroom.name}} </h6>{% endif %}
    {% if user.is_teacher %} {% for obj in user.teachers.classroom.all %}<h6 class="card-subtitle mb-2 badge badge-primary">{{ obj.name }}</h6>{% endfor %}{% endif %}</a>
    <p class="afo">I wish i was a little bit taller, wish i was a baller, wish i had a girl…&nbsp;also.</p>
  </div>
</div>

<div class="card m-0">
<h6 class="bg-default p-3 mb-0"> about :  <a data-toggle="collapse" href="#AboutUser" aria-expanded="true" aria-controls="AboutUser" class="align-text-top text-white pull-right"><small>Hide</small></a></h6>
<div class="card-block p-3 collapse show" id="AboutUser">
  <ul class="cl list-group">
    <li class=" mb-2 list-group-item"><span class="mr-1 mb-5"><i class="fas fa-home mr-2"></i>Adresse</span><a class="text-primary" >{{ user.adresse}}</a></li>
    <li class=" mb-2 list-group-item"><span class="mr-1"><i class="fas fa-venus-mars mr-2"></i>Gender </span><a class="text-primary">{{ user.gender}}</a></li>
    <li class=" mb-2 list-group-item"><span class="mr-1"><i class="fas fa-birthday-cake mr-2"></i>Birth Day </span><a class="text-primary">{{ user.birth_day}}</a></li>
    <li class=" mb-2 list-group-item"><span class="mr-1"><i class="fas fa-map-marker-alt mr-2"></i>Birth Location </span><a class="text-primary">{{ user.birth_location}}</a></li>
  </ul>
</div>
 
</div>
<div class="card m-0">
  <h6 class="bg-default p-3 mb-0"> Teachers :  <a data-toggle="collapse" href="#AboutTeacher" aria-expanded="false" aria-controls="AboutTeacher" class="align-text-top text-white pull-right"><small>SHOW</small></a></h6>
  <div class="card-block p-3 collapse" id="AboutTeacher">
    <ul class="cl list-group">
      {% for obj in user.students.classroom.teacher_set.all %}
      <li class=" mb-2 list-group-item"><a href="{% url 'accounts:profile' obj.user.username %}"><img class="pull-left img-list p-1 mr-2" src="{{ obj.user.avatar.url }}"></a>
      <p class="text-primary">{{ obj.user.first_name }} {{ obj.user.last_name }}</p>
      <p class="badge badge-danger"> {{ obj.module }} </p></li>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="card m-0">
  <h6 class="bg-default p-3 mb-0"> Class Mates :  <a data-toggle="collapse" href="#AboutStudent" aria-expanded="false" aria-controls="AboutStudent" class="align-text-top text-white pull-right"><small>SHOW</small></a></h6>
  <div class="card-block p-3 collapse" id="AboutStudent">
    <ul class="cl list-group">
      {% for obj in user.students.classroom.student_set.all %}
      <li class=" mb-2 list-group-item"><a href="{% url 'accounts:profile' obj.user.username %}"><img class="pull-left img-list p-1 mr-2" src="{{ obj.user.avatar.url }}"></a>
      <p class="text-primary">{{ obj.user.first_name }} {{ obj.user.last_name }}</p>
      <p class="badge badge-danger"> {{ obj.classroom }} </p></li>
      {% endfor %}
    </ul>
  </div>
</div>

src/templates/accounts/mid-section.html
{% load static %}


	{% if messages%}
	{% for msg in messages %}
	<div class="alert bg-success text-white text-center">{{ msg  }} </div>
	{% endfor %}
	{% endif %}
{% if  request.user.is_superuser %}
<div class="fixed-bottom">
	<a href="{% url 'blog:create' %}" class="coffee-button text-white p-4  circle"><i class="fas fa-plus"></i></a>
</div>
<div class="form-container mx-auto">

	<a class="btn btn-block btn-lg bg-default" data-toggle="collapse" href="#blogForm" aria-expanded="false" aria-controls="blogForm">
	add a post
	</a>
	<form class="collapse" id="blogForm" action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<input type="text" name="title" id="id_title" required="" maxlength="120" placeholder=" Enter title here"  class="form-control">
		</div>
		<div class="form-group">
			<textarea name="content" rows="10" id="id_content" cols="40" required="" maxlength="2000" placeholder=" Enter title here"  class="form-control"></textarea>
		</div>
		<div class="form-group">
			<input required type="file" multiple name="images" class="form-control_file">
		</div>
		<button type="submit" class="btn btn-danger btn-round">Submit</button>
	</form>
</div>
</span>
{% endif %}
{% for posts in list %}

{% if posts.title %}
<div class="card d-flex flex-column p-3 bg-white">
	{% if  request.user.is_superuser or request.user == posts.user %}
	<a href="{% url 'blog:post-delete' posts.id %}""><span  class="close-btn blue"><i class="fas fa-times fa-2x"></i></span></a>
	{% endif %}
	<div class=" d-flex">
		<img  class="rounded-circle pi mr-2" src="{{posts.user.avatar.url }}">
		<div>
			<div class="card-top">
				<span class="username text-capitalize"><a href="{% url 'accounts:profile' posts.user.username %}">{{ posts.user.username}}</a></span>
				<span class="timestamp"><a href=" {{ posts.get_absolute_url }} ">{% if posts.updated %}{{ posts.updated|timesince }}{% else %}{{ timestamp|timesince }}{% endif %} ago</a></span>
			</div>
			<div class="card-block">
				<p style="word-break: break-word;" class="card-text text-muted">{{ posts.content|safe|truncatechars:300 }}</p><hr/>
			</div>
			<a href="{% url 'blog:detail' posts.id %}"><img class="card-post-image" src="{{ posts.images.first.image.url }}" alt="Card image cap"></a>
			<div class="card-block">

				<div class="d-flex  flex-row justify-content-between">
					<div >
						<a href="" data-href="{{ posts.get_like_api_url }}" data-likes="{{ posts.like.count }}" class="btn btn-primary btn-icon btn-simple btn-icon-mini btn-round mr-2 like-btn" id="likes-{{posts.id}}"><i class="now-ui-icons ui-2_favourite-28"></i></a><span data-likes="{{ posts.like.count }}"  class="mr-3 like-count"> {{ posts.like.count }} </span>
						<!-- <a href="" class="btn btn-primary btn-icon btn-icon-mini btn-round mr-2"><i class="now-ui-icons ui-2_chat-round"></i></a><span>24</span> -->
					</div>
					<div >
						<a  href="{{ posts.get_absolute_url }}" class="btn btn-primary btn-simple align-self-end">view detail</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endif %}
{% if posts.grade %}

<div class="grade-box bg-default-light mt-5 d-flex flex-row">
	{% if posts.grade < 10 %}
	<span class="grade-box-icon"><i class="fas fa-thumbs-down text-danger"></i></span>
	{% else %}
	<span class="grade-box-icon"><i class="fas fa-thumbs-up text-success"></i></span>
	{% endif %}

		<div class="grade-box-content">
			<span class="grade-box-text">{{ posts.teacher }} : {{ posts.module }}</span>
			<span class="grade-box-number">{{ posts.grade }}/20</span>
			<div class="progress">
				<div class="progress-bar" style="width: calc({{ posts.grade }}*5%)"></div>
			</div>
		</div>
	</div>
	{% endif %}

	{% empty %}
	{% if request.GET.q %}
	<p>no post found</p>
	{% else %}
	<p> no posts yet</p>
	{% endif %}

	{% endfor %}
</div>

src/templates/accounts/post_navbar.html
{% load static %}
{% if request.user == post.user or request.user.is_superuser %}
 <!-- Navbar -->
	    <nav class="navbar navbar-expand-lg bg-default fixed-top p-0 " color-on-scroll="400">
	        <div class="container flex-nowrap">
	            <div >
	            	 <a class="navbar-brand mx-auto" href="#">
	                  <img src="{% static 'img/logo-aladin.png' %}"" width="30" height="30" alt="">
					 	<p>Aladin Private School</p>
	                </a>
	            </div>
	           
	            <form class="form-inline flex-nowrap fb" id="navSearch" action="{% url 'home' %}" method="GET">
	
					<input class="form-control form-control-no-border" type="text" name="q" placeholder='Search...' value="{{ request.GET.q }}">
					<button style="display:none" class="btn btn-primary btn-simple" type='submit' value='search'>Search</button>
				
				</form> 
	            
	           
	            <div class="d-flex fb" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">

	                <ul class="navbar-nav">
	                	 <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'home' %}"><i class="fas fa-home"></i></a>
	                    </li>
	                    <li class="nav-item">
	                    	<a class="nav-link btn-round" href="{% url 'blog:update' post.pk %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>
</a>
	                    </li>
	                    
	                </ul>
	                <div class="nav-item dropdown">
	                       <a class="nav-link dropdown-toggle"  id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	                       	{% if user.avatar %}
	                       	<img style="max-width: 35px; max-height: 35px;" class="rounded-circle" src="{{ request.user.avatar.url }}">
	                       	{% else %}
	                       	{% endif %}
	                         
	                       </a>
	                       <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	                         <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> 
	                       </div>
	                </div>
	            </div>

	        </div>
	    </nav>
	    

{% endif %}

src/templates/accounts/right-section.html
{% load static %}
{% if user.is_student %}
<div class="sticky-top"><hr/>
	{% if events %}
	{% for obj in events %}
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" data-dismiss="alert" class="close" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
		{{ obj.content }}  {{ obj.end}}
	</div>	
	{% endfor %}
	{% endif %}
</div>
{% endif %}
{% if user.is_teacher %}
<div>
	<!-- <form action="{% url 'events:teacher' %}" method="post">{% csrf_token %}
    <div class="input-group ">
    	<select name="user" required="" id="id_user" class="form-control">
    	  <option value="" selected="">---------</option>

    	  <option value="1">pegas</option>

    	  <option value="2">teststudent</option>

    	  <option value="3">testteacher</option>

    	</select>
   	</div>
   	<div class="input-group ">
   		<input type="text" name="content" maxlength="120" required="" id="id_content" class="form-control">
   		
   	</div>
   	<div class="input-group ">
   		<input type="text" name="start" id="id_start" required="" class="form-control ">
   		<a href="#" id="calendarlink0"><i class="far fa-calendar-alt fa-2x"></i></a>
   </div>
   	<div class="input-group ">
   		<input type="text" name="end" id="id_end" required="" class="form-control">
   		<a href="#" id="calendarlink1"><i class="far fa-calendar-alt date-icon"></i></a>
   	</div>



    <input type="submit" value="Save" />
</form> -->
<hr/>
<a href="" class="btn btn-block btn-primary btn-simple">add Event</a>
<hr/>
</div>

{% endif %}