src/blog/urls.py
from django.conf.urls import url 
from django.views.generic.base import RedirectView
from blog import views

urlpatterns = [
	url(r'detail/(?P<pk>\d+)/like', views.PostLikeToggle.as_view(), name='like-toggle'),
	url(r'create/', views.create_post, name='create'),
    url(r'detail/(?P<pk>\d+)', views.PostDetailView.as_view(), name='detail'),

    url(r'update/(?P<pk>\d+)', views.PostUpdateView, name='update'),
    url(r'file/delete/(?P<pk>\d+)', views.image_delete, name='file-delete'),
    url(r'post/delete/(?P<pk>\d+)', views.post_delete, name='post-delete'),
    # url(r'', RedirectView.as_view(url="home")),

]

src/marks/urls.py
from django.conf.urls import url
from marks import views


urlpatterns = [
	
	url(r'update/(?P<pk>[\w.@+-]+)/', views.MarksUpdateView.as_view(), name='marks-update'),
	url(r'list/', views.MarksListView.as_view(), name='marks-list'),
	url(r'create/', views.MarksCreateView.as_view(), name='marks-create'),
	url(r'ajax/' , views.load_teachers , name="load_teachers" )
]
    

src/school/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from accounts  import views as accounts_views
from blog.views import PostListView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    # url(r'^', include('events.urls', namespace='events')),
    url(r'^admin/', admin.site.urls),
    url(r'^signup/student$', accounts_views.StudentSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='student_signup'),
    url(r'^signup/teacher$', accounts_views.TeacherSignUpView.as_view(success_url=reverse_lazy('accounts:profile')), name='teacher_signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'api/blog/', include('blog.api.urls', namespace='api_blog')),
    url(r'blog/', include('blog.urls', namespace='blog')),
    url(r'marks/', include('marks.urls', namespace='marks')),
    url(r'grades/', include('grades.urls', namespace='grade')),
    url(r'events/', include('events.urls', namespace='events')),
    url(r'^$',  accounts_views.HomeListView.as_view(), name='home'),
    #url(r'ckeditor/', include('ckeditor_uploader.urls', )),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/marks/models.py
from django.db import models
from accounts.models  import User,Teacher,Module,Grade

# Create your models here.

class Marks(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	module = models.ForeignKey(Module, on_delete=models.CASCADE) # will change it later to choice_Field
	teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE,)
	grade = models.IntegerField()
	date = models.DateField(auto_now=False, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True,)

	def __str__(self):
		return self.user.first_name + " " + self.user.last_name

	class Meta:
		ordering = ["-timestamp" ,]
		verbose_name_plural = "Marks"

src/marks/forms.py
from django import forms
from accounts.models import User,Teacher,Module
from .models import Marks


class MarksForm(forms.ModelForm):
	
	class Meta :
		model = Marks
		fields = ['user','module','teacher','grade']


	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['teacher'].queryset = Teacher.objects.none()

		if 'module' in self.data:
			try:
				module_id = int(self.data.get('module'))
				self.fields['teacher'].queryset = Teacher.objects.filter(module_id=module_id)
			except (ValueError, TypeError):
				pass  # invalid input from the client; ignore and fallback to empty City queryset
		elif self.instance.pk:
			self.fields['teacher'].queryset = self.instance.module.teacher_set

src/marks/views.py
from django.shortcuts import render
from .models import Marks
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .forms import MarksForm
from accounts.models import User,Teacher,Module
# Create your views here.


class MarksListView(ListView):
	model = Marks
	context_object_name = "marks"
	template_name = "marks_list.html"

class MarksCreateView(CreateView):

	model = Marks
	template_name = "marks_create.html"
	form_class = MarksForm
	success_url = reverse_lazy('home')

class MarksUpdateView(UpdateView):

	model = Marks
	template_name = "marks_update.html"
	form_class = MarksForm
	success_url = reverse_lazy('home')


def load_teachers(request):
	module_id= request.GET.get("module")
	teachers = Teacher.objects.filter(module_id=module_id)
	return render(request, 'teacher_dropdown_list_options.html', {'teachers': teachers})

src/marks/templates/marks_create.html
{% extends 'accounts/base.html' %}
{% load static %}



{% block content %} 
  <h2>marks Form</h2>
  <form method="post" id="marksForm" data-teachers-url="{% url 'marks:load_teachers' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
   
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_module").change(function () {
      var url = $("#marksForm").attr("data-teachers-url");  // get the url of the `load_cities` view
      var moduleId = $(this).val();  // get the selected country ID from the HTML input
      console.log(moduleId);

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'module': moduleId       // add the country id to the GET parameters

        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_teacher").html(data);  // replace the contents of the city input with the data that came from the server
          console.log(data)
        }
      });

    });
  </script>
{% endblock %}

src/marks/templates/marks_list.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content%}

<div class="container">
	<h3>marks list</h3>
	<div>
		{% for m in marks %}
			<p> {{ m.id }} </p>
			<p>{{ m.user }}</p>
			<p>{{ m.module }}</p>
			<p>{{ m.teacher }}</p>
			<p>{{ m.grade }}</p><hr/><hr/><hr/>
			
		{% endfor %}
	</div>
</div>

{% endblock %}

src/marks/templates/marks_update.html
{% extends 'accounts/base.html' %}
{% load static %}



{% block content %} 
  <h2>marks Form</h2>
  <form method="post" id="marksForm" data-teachers-url="{% url 'marks:load_teachers' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
   
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_module").change(function () {
      var url = $("#marksForm").attr("data-teachers-url");  // get the url of the `load_cities` view
      var moduleId = $(this).val();  // get the selected country ID from the HTML input
      console.log(moduleId);

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'module': moduleId       // add the country id to the GET parameters

        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_teacher").html(data);  // replace the contents of the city input with the data that came from the server
          console.log(data)
        }
      });

    });
  </script>
{% endblock %}

src/marks/templates/teacher_dropdown_list_options.html
<option value="">---------</option>
{% for teacher in teachers %}
<option value="{{ teacher.pk }}">{{ teacher.user.first_name }}</option>
{% endfor %}